import { ContentService } from '../../services/content.service';
import User from '../../models/user.model';
import Content from '../../models/content.model';

describe('ContentService', () => {
  let contentService: ContentService;
  let testUser: any;

  beforeEach(async () => {
    contentService = new ContentService();
    testUser = await User.create({
      email: 'test@example.com',
      password: 'hashedpassword',
      name: 'Test User',
      usageCredits: 10
    });
  });

  describe('generateContent', () => {
    it('should generate content successfully', async () => {
      const params = {
        topic: 'AI in Healthcare',
        tone: 'professional',
        wordCount: 800,
        keywords: ['artificial intelligence', 'healthcare'],
        type: 'blog'
      };

      const result = await contentService.generateContent(testUser._id.toString(), params);

      expect(result).toBeDefined();
      expect(result.title).toBe('Test Blog Post Title');
      expect(result.content).toBe('This is test content generated by AI.');
      expect(result.wordCount).toBe(50);
      expect(result.readingTime).toBe(1);

      // Check if content was saved to database
      const savedContent = await Content.findOne({ userId: testUser._id });
      expect(savedContent).toBeTruthy();
      expect(savedContent?.title).toBe('Test Blog Post Title');

      // Check if credits were deducted
      const updatedUser = await User.findById(testUser._id);
      expect(updatedUser?.usageCredits).toBe(9);
    });

    it('should throw error when user has insufficient credits', async () => {
      // Set user credits to 0
      testUser.usageCredits = 0;
      await testUser.save();

      const params = {
        topic: 'Test Topic',
        tone: 'professional',
        wordCount: 500,
        keywords: ['test'],
        type: 'blog'
      };

      await expect(
        contentService.generateContent(testUser._id.toString(), params)
      ).rejects.toThrow('Insufficient credits');
    });
  });

  describe('getContent', () => {
    beforeEach(async () => {
      // Create test content
      await Content.create([
        {
          userId: testUser._id,
          title: 'Test Post 1',
          content: 'Content 1',
          status: 'draft',
          type: 'blog',
          wordCount: 100
        },
        {
          userId: testUser._id,
          title: 'Test Post 2',
          content: 'Content 2',
          status: 'published',
          type: 'blog',
          wordCount: 200
        }
      ]);
    });

    it('should get paginated content', async () => {
      const result = await contentService.getContent(testUser._id.toString(), {
        page: 1,
        limit: 10
      });

      expect(result.data).toHaveLength(2);
      expect(result.pagination.total).toBe(2);
      expect(result.pagination.pages).toBe(1);
    });

    it('should filter content by status', async () => {
      const result = await contentService.getContent(testUser._id.toString(), {
        status: 'draft',
        page: 1,
        limit: 10
      });

      expect(result.data).toHaveLength(1);
      expect(result.data[0].status).toBe('draft');
    });
  });

  describe('getContentStats', () => {
    beforeEach(async () => {
      await Content.create([
        {
          userId: testUser._id,
          title: 'Draft Post',
          content: 'Content',
          status: 'draft',
          wordCount: 100,
          readingTime: 1
        },
        {
          userId: testUser._id,
          title: 'Published Post',
          content: 'Content',
          status: 'published',
          wordCount: 200,
          readingTime: 2
        }
      ]);
    });

    it('should return correct content statistics', async () => {
      const stats = await contentService.getContentStats(testUser._id.toString());

      expect(stats.total).toBe(2);
      expect(stats.published).toBe(1);
      expect(stats.draft).toBe(1);
      expect(stats.scheduled).toBe(0);
      expect(stats.totalWords).toBe(300);
      expect(stats.averageReadingTime).toBe(2);
    });
  });
});